# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wavemeter_dashboard/view/ui/ui_channel_name_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChannelNameWidget(object):
    def setupUi(self, ChannelNameWidget):
        ChannelNameWidget.setObjectName("ChannelNameWidget")
        ChannelNameWidget.resize(152, 80)
        self.gridLayout = QtWidgets.QGridLayout(ChannelNameWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.monBtn = ToggleButton(ChannelNameWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monBtn.sizePolicy().hasHeightForWidth())
        self.monBtn.setSizePolicy(sizePolicy)
        self.monBtn.setObjectName("monBtn")
        self.gridLayout.addWidget(self.monBtn, 0, 2, 1, 1)
        self.setBtn = QtWidgets.QPushButton(ChannelNameWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setBtn.sizePolicy().hasHeightForWidth())
        self.setBtn.setSizePolicy(sizePolicy)
        self.setBtn.setObjectName("setBtn")
        self.gridLayout.addWidget(self.setBtn, 1, 2, 1, 1)
        self.channNameLabel = ChannelNameLabel(ChannelNameWidget)
        self.channNameLabel.setObjectName("channNameLabel")
        self.gridLayout.addWidget(self.channNameLabel, 0, 1, 2, 1)
        self.indicatorLabel = QtWidgets.QLabel(ChannelNameWidget)
        self.indicatorLabel.setText("")
        self.indicatorLabel.setObjectName("indicatorLabel")
        self.gridLayout.addWidget(self.indicatorLabel, 0, 0, 2, 1)

        self.retranslateUi(ChannelNameWidget)
        QtCore.QMetaObject.connectSlotsByName(ChannelNameWidget)

    def retranslateUi(self, ChannelNameWidget):
        _translate = QtCore.QCoreApplication.translate
        ChannelNameWidget.setWindowTitle(_translate("ChannelNameWidget", "Form"))
        self.monBtn.setText(_translate("ChannelNameWidget", "MON"))
        self.setBtn.setText(_translate("ChannelNameWidget", "SET"))
        self.channNameLabel.setText(_translate("ChannelNameWidget", "TextLabel"))
from wavemeter_dashboard.view.widgets.misc import ChannelNameLabel, ToggleButton
