# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wavemeter_dashboard/view/ui/ui_dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dashboard(object):
    def setupUi(self, dashboard):
        dashboard.setObjectName("dashboard")
        dashboard.resize(878, 784)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dashboard.sizePolicy().hasHeightForWidth())
        dashboard.setSizePolicy(sizePolicy)
        dashboard.setStyleSheet("")
        self.gridLayout_3 = QtWidgets.QGridLayout(dashboard)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_2 = QtWidgets.QFrame(dashboard)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleLabel = TitleLabel(dashboard)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_3.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.monBtn = ToggleButton(dashboard)
        self.monBtn.setObjectName("monBtn")
        self.horizontalLayout_3.addWidget(self.monBtn)
        self.saveSettingsBtn = QtWidgets.QPushButton(dashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSettingsBtn.sizePolicy().hasHeightForWidth())
        self.saveSettingsBtn.setSizePolicy(sizePolicy)
        self.saveSettingsBtn.setObjectName("saveSettingsBtn")
        self.horizontalLayout_3.addWidget(self.saveSettingsBtn)
        self.closeWindowButton = RedButton(dashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeWindowButton.sizePolicy().hasHeightForWidth())
        self.closeWindowButton.setSizePolicy(sizePolicy)
        self.closeWindowButton.setObjectName("closeWindowButton")
        self.horizontalLayout_3.addWidget(self.closeWindowButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(dashboard)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.channelGridLayout = QtWidgets.QGridLayout()
        self.channelGridLayout.setContentsMargins(20, 20, 20, 20)
        self.channelGridLayout.setObjectName("channelGridLayout")
        self.verticalLayout.addLayout(self.channelGridLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.addChannelBtn = QtWidgets.QPushButton(dashboard)
        self.addChannelBtn.setObjectName("addChannelBtn")
        self.horizontalLayout.addWidget(self.addChannelBtn)
        self.gridLayout_3.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 4, 0, 1, 1)

        self.retranslateUi(dashboard)
        QtCore.QMetaObject.connectSlotsByName(dashboard)

    def retranslateUi(self, dashboard):
        _translate = QtCore.QCoreApplication.translate
        dashboard.setWindowTitle(_translate("dashboard", "Form"))
        self.titleLabel.setText(_translate("dashboard", "WAVEMETER CHANNEL VIEW"))
        self.monBtn.setText(_translate("dashboard", "MONITOR"))
        self.saveSettingsBtn.setText(_translate("dashboard", "SAVE"))
        self.closeWindowButton.setText(_translate("dashboard", "X"))
        self.addChannelBtn.setText(_translate("dashboard", "ADD CHANNEL"))
from wavemeter_dashboard.view.widgets.misc import RedButton, TitleLabel, ToggleButton
