# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wavemeter_dashboard/view/ui/ui_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(262, 138)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog.sizePolicy().hasHeightForWidth())
        dialog.setSizePolicy(sizePolicy)
        self.mainLayout = QtWidgets.QVBoxLayout(dialog)
        self.mainLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.titleLabel = DialogTitleLabel(dialog)
        self.titleLabel.setObjectName("titleLabel")
        self.mainLayout.addWidget(self.titleLabel)
        self.dialogLayout = QtWidgets.QVBoxLayout()
        self.dialogLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.dialogLayout.setContentsMargins(20, 20, 20, 20)
        self.dialogLayout.setObjectName("dialogLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelBtn = QtWidgets.QPushButton(dialog)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.applyBtn = QtWidgets.QPushButton(dialog)
        self.applyBtn.setObjectName("applyBtn")
        self.horizontalLayout.addWidget(self.applyBtn)
        self.dialogLayout.addLayout(self.horizontalLayout)
        self.mainLayout.addLayout(self.dialogLayout)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Form"))
        self.titleLabel.setText(_translate("dialog", "Title"))
        self.cancelBtn.setText(_translate("dialog", "CANCEL"))
        self.applyBtn.setText(_translate("dialog", "APPLY"))
from wavemeter_dashboard.view.widgets.misc import DialogTitleLabel
