# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wavemeter_dashboard/view/ui/ui_data_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dataSelect(object):
    def setupUi(self, dataSelect):
        dataSelect.setObjectName("dataSelect")
        dataSelect.resize(609, 260)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dataSelect.sizePolicy().hasHeightForWidth())
        dataSelect.setSizePolicy(sizePolicy)
        dataSelect.setMinimumSize(QtCore.QSize(609, 260))
        self.addBtn = QtWidgets.QPushButton(dataSelect)
        self.addBtn.setGeometry(QtCore.QRect(270, 90, 61, 31))
        self.addBtn.setObjectName("addBtn")
        self.label = QtWidgets.QLabel(dataSelect)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dataSelect)
        self.label_2.setGeometry(QtCore.QRect(360, 10, 101, 16))
        self.label_2.setObjectName("label_2")
        self.deleteBtn = QtWidgets.QPushButton(dataSelect)
        self.deleteBtn.setGeometry(QtCore.QRect(350, 220, 251, 32))
        self.deleteBtn.setObjectName("deleteBtn")
        self.upBtn = QtWidgets.QPushButton(dataSelect)
        self.upBtn.setGeometry(QtCore.QRect(350, 180, 101, 32))
        self.upBtn.setObjectName("upBtn")
        self.downBtn = QtWidgets.QPushButton(dataSelect)
        self.downBtn.setGeometry(QtCore.QRect(500, 180, 101, 32))
        self.downBtn.setObjectName("downBtn")
        self.candidateList = QtWidgets.QListWidget(dataSelect)
        self.candidateList.setGeometry(QtCore.QRect(10, 30, 231, 141))
        self.candidateList.setObjectName("candidateList")
        self.selectedList = QtWidgets.QListWidget(dataSelect)
        self.selectedList.setGeometry(QtCore.QRect(360, 30, 231, 141))
        self.selectedList.setObjectName("selectedList")

        self.retranslateUi(dataSelect)
        QtCore.QMetaObject.connectSlotsByName(dataSelect)

    def retranslateUi(self, dataSelect):
        _translate = QtCore.QCoreApplication.translate
        dataSelect.setWindowTitle(_translate("dataSelect", "Form"))
        self.addBtn.setText(_translate("dataSelect", "ADD"))
        self.label.setText(_translate("dataSelect", "CANDIDATES"))
        self.label_2.setText(_translate("dataSelect", "SELECTED"))
        self.deleteBtn.setText(_translate("dataSelect", "DELETE"))
        self.upBtn.setText(_translate("dataSelect", "UP"))
        self.downBtn.setText(_translate("dataSelect", "DOWN"))
