# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wavemeter_dashboard/view/ui/ui_single_channel_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_singleChannelView(object):
    def setupUi(self, singleChannelView):
        singleChannelView.setObjectName("singleChannelView")
        singleChannelView.resize(664, 530)
        self.gridLayout = QtWidgets.QGridLayout(singleChannelView)
        self.gridLayout.setObjectName("gridLayout")
        self.titleLabel = TitleLabel(singleChannelView)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.toDashboardBtn = QtWidgets.QPushButton(singleChannelView)
        self.toDashboardBtn.setObjectName("toDashboardBtn")
        self.gridLayout.addWidget(self.toDashboardBtn, 0, 3, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(singleChannelView)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 638, 470))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setObjectName("mainLayout")
        self.graphLayout = QtWidgets.QVBoxLayout()
        self.graphLayout.setObjectName("graphLayout")
        self.graphicsView = GraphicsLayoutWidget(self.scrollAreaWidgetContents)
        self.graphicsView.setObjectName("graphicsView")
        self.graphLayout.addWidget(self.graphicsView)
        self.bigFreqLabel = FreqWavelengthLabel(self.scrollAreaWidgetContents)
        self.bigFreqLabel.setObjectName("bigFreqLabel")
        self.graphLayout.addWidget(self.bigFreqLabel)
        self.mainLayout.addLayout(self.graphLayout)
        self.setupLayout = QtWidgets.QVBoxLayout()
        self.setupLayout.setObjectName("setupLayout")
        self.channelNameLabel = ChannelNameLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelNameLabel.sizePolicy().hasHeightForWidth())
        self.channelNameLabel.setSizePolicy(sizePolicy)
        self.channelNameLabel.setObjectName("channelNameLabel")
        self.setupLayout.addWidget(self.channelNameLabel)
        self.alertLabel = ChannelAlertLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alertLabel.sizePolicy().hasHeightForWidth())
        self.alertLabel.setSizePolicy(sizePolicy)
        self.alertLabel.setObjectName("alertLabel")
        self.setupLayout.addWidget(self.alertLabel)
        self.channelSetupWidget = ChannelSetupWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelSetupWidget.sizePolicy().hasHeightForWidth())
        self.channelSetupWidget.setSizePolicy(sizePolicy)
        self.channelSetupWidget.setObjectName("channelSetupWidget")
        self.setupLayout.addWidget(self.channelSetupWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.resetBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.resetBtn.setObjectName("resetBtn")
        self.horizontalLayout_2.addWidget(self.resetBtn)
        self.applyBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.applyBtn.setObjectName("applyBtn")
        self.horizontalLayout_2.addWidget(self.applyBtn)
        self.setupLayout.addLayout(self.horizontalLayout_2)
        self.monBtn = ToggleButton(self.scrollAreaWidgetContents)
        self.monBtn.setObjectName("monBtn")
        self.setupLayout.addWidget(self.monBtn)
        self.mainLayout.addLayout(self.setupLayout)
        self.horizontalLayout_3.addLayout(self.mainLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.selectGraphBtn = QtWidgets.QPushButton(singleChannelView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectGraphBtn.sizePolicy().hasHeightForWidth())
        self.selectGraphBtn.setSizePolicy(sizePolicy)
        self.selectGraphBtn.setObjectName("selectGraphBtn")
        self.gridLayout.addWidget(self.selectGraphBtn, 0, 2, 1, 1)

        self.retranslateUi(singleChannelView)
        QtCore.QMetaObject.connectSlotsByName(singleChannelView)

    def retranslateUi(self, singleChannelView):
        _translate = QtCore.QCoreApplication.translate
        singleChannelView.setWindowTitle(_translate("singleChannelView", "Form"))
        self.titleLabel.setText(_translate("singleChannelView", "SINGEL CHANNEL VIEW"))
        self.toDashboardBtn.setText(_translate("singleChannelView", "BACK TO DASHBOARD"))
        self.bigFreqLabel.setText(_translate("singleChannelView", "FREQ"))
        self.channelNameLabel.setText(_translate("singleChannelView", "CHANNEL"))
        self.alertLabel.setText(_translate("singleChannelView", "ALERT"))
        self.resetBtn.setText(_translate("singleChannelView", "RESET"))
        self.applyBtn.setText(_translate("singleChannelView", "APPLY"))
        self.monBtn.setText(_translate("singleChannelView", "MONITOR"))
        self.selectGraphBtn.setText(_translate("singleChannelView", "SELECT GRAPH"))
from pyqtgraph import GraphicsLayoutWidget
from wavemeter_dashboard.view.widgets.channel_alert_label import ChannelAlertLabel
from wavemeter_dashboard.view.widgets.channel_setup_widget import ChannelSetupWidget
from wavemeter_dashboard.view.widgets.freq_wavelength_label import FreqWavelengthLabel
from wavemeter_dashboard.view.widgets.misc import ChannelNameLabel, TitleLabel, ToggleButton
